### ISSUE TITLE
使用插件后文章内容无法渲染

### ISSUE THREAD

**Issue by aligu99** [EVINK/hexo-encrypted-plugin#1]
大佬好，很喜欢你这款hexo密码插件，但是安装后发现有两个问题：

1、安装插件并添加文章密码后，运行hexo clean后，再运行hexo g出现如下错误：

`Error: ENOENT: no such file or directory, mkdir 'public/@encrypted/'
    at Object.mkdirSync (node:fs:1398:3)
`

需要手动创建这个目录`mkdir -p public/@encrypted/`，然后才能正常运行。

2、正常运行后，在本地http://localhost:4000/ 生成网页输入密码进入文章页，文章markdown内容没有渲染，如下图：

加密码前：
![](https://bu.dusays.com/2024/08/25/66cad4c062092.webp)

加密码后：
![](https://bu.dusays.com/2024/08/25/66cad4c05857d.webp)

以上，并非计算机相关专业，不是很懂这些，烦请大佬解惑，感谢。

**Comment by EVINK** [comment]
Hi, 请你博客的根目录下尝试以下命令：

$ rm -rf public/
$ rm db.json
$ hexo server

**Comment by aligu99** [comment]
> Hi, 请你博客的根目录下尝试以下命令：
> 
> $ rm -rf public/ $ rm db.json $ hexo server

你好，我的是windows powershell，部署到vercel服务器的，好像这个linux命令用不了，然后gpt说用Remove-Item -Recurse -Force .\public\这个命令删除静态文件后也没用。

后来我手动创建public/@encrypted/，先把markdown内容渲染成html再放回文章中就可以了，就是麻烦，我的博客域名是https://tech.aligu.top, encrypt密码是hello，麻烦大佬看看。

**Comment by EVINK** [comment]
Hi, 谢谢你的反馈。

> 1、安装插件并添加文章密码后，运行hexo clean后，再运行hexo g出现如下错误：
Error: ENOENT: no such file or directory, mkdir 'public/@encrypted/' at Object.mkdirSync (node:fs:1398:3) 
需要手动创建这个目录mkdir -p public/@encrypted/，然后才能正常运行。

此 bug 已修复，请到根目录定位到 package.json 文件。找到 hexo-encrypted-plugin": "0.0.10"这一行,  将其改为 hexo-encrypted-plugin": "0.0.11"，再次运行 `npm install` 即可更新到新版本。

在 Windows 下，你可以尝试直接右键删除 /public/ 文件夹和 db.json 文件。

接着新建一篇文章，并测试加密和渲染功能是否运行正确。

如果仍然存在渲染问题，欢迎回来告知。

附带我使用的环境

> hexo: 5.4.2
> hexo-cli: 4.2.0
> node: 21.2.0

**Comment by aligu99** [comment]
> Hi, 谢谢你的反馈。
> 
> > 1、安装插件并添加文章密码后，运行hexo clean后，再运行hexo g出现如下错误：
> > Error: ENOENT: no such file or directory, mkdir 'public/@encrypted/' at Object.mkdirSync (node:fs:1398:3)
> > 需要手动创建这个目录mkdir -p public/@encrypted/，然后才能正常运行。
> 
> 此 bug 已修复，请到根目录定位到 package.json 文件。找到 hexo-encrypted-plugin": "0.0.10"这一行, 将其改为 hexo-encrypted-plugin": "0.0.11"，再次运行 `npm install` 即可更新到新版本。
> 
> 在 Windows 下，你可以尝试直接右键删除 /public/ 文件夹和 db.json 文件。
> 
> 接着新建一篇文章，并测试加密和渲染功能是否运行正确。
> 
> 如果仍然存在渲染问题，欢迎回来告知。
> 
> 附带我使用的环境
> 
> > hexo: 5.4.2
> > hexo-cli: 4.2.0
> > node: 21.2.0

你好，感谢大佬更新插件，按照您的方法已经能够正常添加密码并渲染了，发现还有两个小问题，Demo放在我的博客https://tech.aligu.top/, 置顶处了：

1、加密文章中的代码框没有渲染出来，对比了更新后加密文章和未加密文章

2、加密文章最后一行会出现小框框，不知道是不是多了`<div>`标签

我的使用环境是：
hexo: 7.3.0
node:18.17.1
用的高亮代码框highlight: https://cdn.bootcdn.net/ajax/libs/highlight.js/9.16.2/highlight.min.js

**Comment by EVINK** [comment]
Hi,

> 加密文章中的代码框没有渲染出来，对比了更新后加密文章和未加密文章

对于你使用的这个脚本，它是在页面中运行时渲染，但在页面加载时，加密的内容对于此脚本是乱码，而你输入密码还原内容后，由于并没有一个触发器，所以你这个 highlight 脚本不会再次被执行，导致渲染失败。你可以选用下面方法中的其中一个，来解决这个问题：

1. 替换成一个在文章生成时就渲染的hexo插件。（也即执行 hexo -g 时就把样式渲染好)
2. 或者，在加密文章的底部手动再次引入这个script, 如:
```
---
...
password: 1234
---

...your content here....

<script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/9.16.2/highlight.min.js"><script/>
```

这个原理是在内容被还原后，这个 script 会被再执行一次。

> 加密文章最后一行会出现小框框，不知道是不是多了\<div>标签

这个插件使用的加密方法会导致这种情况

**Comment by aligu99** [comment]
> Hi,
> 
> > 加密文章中的代码框没有渲染出来，对比了更新后加密文章和未加密文章
> 
> 对于你使用的这个脚本，它是在页面中运行时渲染，但在页面加载时，加密的内容对于此脚本是乱码，而你输入密码还原内容后，由于并没有一个触发器，所以你这个 highlight 脚本不会再次被执行，导致渲染失败。你可以选用下面方法中的其中一个，来解决这个问题：
> 
> 1. 替换成一个在文章生成时就渲染的hexo插件。（也即执行 hexo -g 时就把样式渲染好)
> 2. 或者，在加密文章的底部手动再次引入这个script, 如:
> 
> ```
> ---
> ...
> password: 1234
> ---
> 
> ...your content here....
> 
> <script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/9.16.2/highlight.min.js"><script/>
> ```
> 
> 这个原理是在内容被还原后，这个 script 会被再执行一次。
> 
> > 加密文章最后一行会出现小框框，不知道是不是多了<div>标签
> 
> 这个插件使用的加密方法会导致这种情况

你好，感谢您的耐心解答，刚才我把script放在文章末尾没有生效：
`<script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/9.16.2/highlight.min.js"></script>`

不过我把加密前的文章先hexo g提前渲染出静态文件，再把代码框部分html复制到markdown文章中使用，然后加密就可以了
https://tech.aligu.top/,  一般博客文章代码还是很少加密的🤭

再次感谢大佬的加密插件和耐心解答！
